### ISSUE TITLE
exp start shows error

### ISSUE THREAD

**Issue by walter211** [allpwrfulroot/yaba-social#6]
[exp] TypeError: undefined is not an object (evaluating 'route.routeName')

This error is located at:
    in DrawerView (at DrawerNavigator.js:127)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:210)
    in NavigationContainer (at SceneView.js:31)
    in SceneView (at CardStack.js:412)
    in RCTView (at View.js:113)
    in View (at CardStack.js:411)
    in RCTView (at View.js:113)
    in View (at CardStack.js:410)
    in RCTView (at View.js:113)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:454)
    in RCTView (at View.js:113)
    in View (at CardStack.js:383)
    in RCTView (at View.js:113)
    in View (at CardStack.js:382)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:49)
    in CardStackTransitioner (at StackNavigator.js:60)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:210)
    in NavigationContainer (at SceneView.js:31)
    in SceneView (at CardStack.js:423)
    in RCTView (at View.js:113)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:454)
    in RCTView (at View.js:113)
    in View (at CardStack.js:383)
    in RCTView (at View.js:113)
    in View (at CardStack.js:382)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:49)
    in CardStackTransitioner (at StackNavigator.js:60)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:210)
    in NavigationContainer (at App.js:62)
    in RCTView (at View.js:113)
    in View (at App.js:59)
    in QueryRecyclerProvider (created by ApolloProvider)
    in ApolloProvider (at App.js:58)
    in App (at registerRootComponent.js:34)
    in RootErrorBoundary (at registerRootComponent.js:33)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
- node_modules/react-navigation/src/routers/createConfigGetter.js:51:10 in <unknown>
- node_modules/react-navigation/src/views/Drawer/DrawerView.js:190:6 in render
- node_modules/react-native/Libraries/Renderer/ReactNativeFiber-dev.js:1667:86 in finishClassComponent
- node_modules/react-native/Libraries/Renderer/ReactNativeFiber-dev.js:2528:33 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/ReactNativeFiber-dev.js:2554:141 in workLoop
- node_modules/react-native/Libraries/Renderer/ReactNativeFiber-dev.js:73:23 in _invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/ReactNativeFiber-dev.js:47:40 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/ReactNativeFiber-dev.js:2593:41 in performWork
- node_modules/react-native/Libraries/Renderer/ReactNativeFiber-dev.js:2728:101 in scheduleUpdateImpl
- node_modules/react-native/Libraries/Renderer/ReactNativeFiber-dev.js:1514:90 in enqueueSetState
- node_modules/react/cjs/react.development.js:218:31 in setState
* App.js:50:18 in _loadAssetsAsync$
- node_modules/regenerator-runtime/runtime.js:63:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:337:30 in invoke
- ... 13 more stack frames from framework internals

**Comment by allpwrfulroot** [comment]
K! Can you say more about how this error occurred? Was this a fresh clone, and which version of react-navigation? The error is pointing towards the react-navigation components, not the app, so it's likely some change on that end. I can hopefully get time to update things in a week or two, or a PR would be welcome!

**Comment by walter211** [comment]
"react-navigation": "1.0.0-beta.21",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",

Could you make a redux integated change to this repo, I met coufesed route managad problem...headace

**Comment by allpwrfulroot** [comment]
The purpose of this example app is partly to show the use of `apollo-link-state`, which ideally replaces redux. Hence, redux will not be integrated here.

Updating to beta.22 in just a moment; fixed the breaking change for the Drawer with the [recommended solution](https://github.com/react-community/react-navigation/issues/3149#issuecomment-352862563).
